name: Fibonacci Even Sum Test

# ======================================================
# GitHub Actions CI/CD Pipeline
# @author Hüseyin ASLIM <22098618@mail.baskent.edu.tr>
# ======================================================

on:
  push:
    branches:
      - develop
      - "*"
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
          - os: macos-latest
            python-version: "3.8"
          - os: macos-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.os == 'macos-latest' ? 'arm64' : 'x64' }}

      - name: Verify Files Exist
        run: ls -R fibonacci_even_sum || echo "No files found"

      - name: Install dependencies (Ubuntu/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov flake8
        shell: bash

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }
          pip install pytest pytest-cov flake8
        shell: pwsh

      - name: Run Linting
        shell: bash
        run: |
          if [ -f fibonacci_even_sum/fibonacci_even_sum.py ] && [ -f fibonacci_even_sum/test_fibonacci_even_sum.py ]; then
            flake8 fibonacci_even_sum/fibonacci_even_sum.py fibonacci_even_sum/test_fibonacci_even_sum.py;
          else
            echo "Linting skipped due to missing files";
          fi

      - name: Run Fibonacci Even Sum Tests with Coverage
        shell: bash
        run: |
          if [ -f fibonacci_even_sum/test_fibonacci_even_sum.py ]; then
            pytest --cov=fibonacci_even_sum fibonacci_even_sum/test_fibonacci_even_sum.py;
          else
            echo "Tests skipped due to missing files";
          fi

      - name: Upload Coverage Report
        if: success()
        uses: codecov/codecov-action@v3
